### ISSUE TITLE
목차 추가 문의

### ISSUE THREAD

**Issue by Kaintels** [teddylee777/machine-learning#14]
안녕하세요.
다름이 아니라 repository의 README.md 파일이 내용 추가로 점점 길어짐에 따라 원하는 내용을 바로 확인하기 쉽지 않을 것 같아 다음과 같이 주제별 밑 부분에 목차를 넣어 보았는데 괜찮은지 문의드립니다.

![image](https://user-images.githubusercontent.com/38157496/91539421-41483f80-e954-11ea-9022-1f5d2800e8b8.png)

pull request 전에 먼저 이슈로 문의를 드립니다.
괜찮으시다면 pull request 드리도록 하겠습니다.

감사합니다!

**Comment by teddylee777** [comment]
네~ 너무 좋을 것 같은데요~? ㅎㅎ 제안 감사합니다~ pull 날려 주십쇼~!!
